# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5417e2e19a2543f484a68cd5877bdfbf02ba0b3e314ca0aee58b4c08d35394db66dabad80beb537d9e4a12f07e0aa933b9858d2bc68845ce9eee142d1ee2b4

test:
  secret_key_base: f6f97a2d29ccfd10acd467a53dfeeea07d28fc71fa6a2dd4e60d6c7072ad0cd0850feeff57fef887866011f7af18ea47787b868a9c2e8a4924080b58d410afa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
